# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 589)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputfield = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.outputfield.setFont(font)
        self.outputfield.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhTime)
        self.outputfield.setObjectName("outputfield")
        self.verticalLayout.addWidget(self.outputfield)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1020, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuConfig = QtWidgets.QMenu(self.menuBar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuCommand = QtWidgets.QMenu(self.menuBar)
        self.menuCommand.setObjectName("menuCommand")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionSerial_port = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionSerial_port.setFont(font)
        self.actionSerial_port.setObjectName("actionSerial_port")
        self.actionG_dump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionG_dump.setFont(font)
        self.actionG_dump.setObjectName("actionG_dump")
        self.actionEvent_history = QtWidgets.QAction(MainWindow)
        self.actionEvent_history.setObjectName("actionEvent_history")
        self.actionabout_Platform1_UI = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionabout_Platform1_UI.setFont(font)
        self.actionabout_Platform1_UI.setObjectName("actionabout_Platform1_UI")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionCheck_FW_revision = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionCheck_FW_revision.setFont(font)
        self.actionCheck_FW_revision.setObjectName("actionCheck_FW_revision")
        self.actionForce_analysis_mode = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionForce_analysis_mode.setFont(font)
        self.actionForce_analysis_mode.setObjectName("actionForce_analysis_mode")
        self.actionBattery_test = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionBattery_test.setFont(font)
        self.actionBattery_test.setObjectName("actionBattery_test")
        self.actionChange_value = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionChange_value.setFont(font)
        self.actionChange_value.setObjectName("actionChange_value")
        self.actionSkip_HD2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionSkip_HD2.setFont(font)
        self.actionSkip_HD2.setObjectName("actionSkip_HD2")
        self.actionSkip_2_Point_Cal = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionSkip_2_Point_Cal.setFont(font)
        self.actionSkip_2_Point_Cal.setObjectName("actionSkip_2_Point_Cal")
        self.actionAll_Seriap_output_ON = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAll_Seriap_output_ON.setFont(font)
        self.actionAll_Seriap_output_ON.setObjectName("actionAll_Seriap_output_ON")
        self.actionMulti_commands = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionMulti_commands.setFont(font)
        self.actionMulti_commands.setObjectName("actionMulti_commands")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionSave_2.setFont(font)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit_2.setFont(font)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuConfig.addAction(self.actionSerial_port)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionOpen)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionClose)
        self.menuCommand.addAction(self.actionAll_Seriap_output_ON)
        self.menuCommand.addAction(self.actionG_dump)
        self.menuCommand.addAction(self.actionCheck_FW_revision)
        self.menuCommand.addAction(self.actionForce_analysis_mode)
        self.menuCommand.addAction(self.actionBattery_test)
        self.menuCommand.addAction(self.actionChange_value)
        self.menuCommand.addAction(self.actionMulti_commands)
        self.menuCommand.addAction(self.actionSkip_HD2)
        self.menuCommand.addAction(self.actionSkip_2_Point_Cal)
        self.menuAbout.addAction(self.actionabout_Platform1_UI)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuConfig.menuAction())
        self.menuBar.addAction(self.menuCommand.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionSave.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Platform1 Serial UI"))
        self.outputfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Tahoma\';\"><br /></p></body></html>"))
        self.menuConfig.setTitle(_translate("MainWindow", "串口配置"))
        self.menuCommand.setTitle(_translate("MainWindow", "命令"))
        self.menuAbout.setTitle(_translate("MainWindow", "关于"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSerial_port.setText(_translate("MainWindow", "串口配置"))
        self.actionG_dump.setText(_translate("MainWindow", "获取database"))
        self.actionEvent_history.setText(_translate("MainWindow", "Event history"))
        self.actionabout_Platform1_UI.setText(_translate("MainWindow", "关于Platform1 UI"))
        self.actionOpen.setText(_translate("MainWindow", "打开串口"))
        self.actionClose.setText(_translate("MainWindow", "关闭串口"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionCheck_FW_revision.setText(_translate("MainWindow", "软件版本"))
        self.actionForce_analysis_mode.setText(_translate("MainWindow", "强制分析模式"))
        self.actionBattery_test.setText(_translate("MainWindow", "低电压测试"))
        self.actionChange_value.setText(_translate("MainWindow", "数据更改"))
        self.actionSkip_HD2.setText(_translate("MainWindow", "跳过HD2"))
        self.actionSkip_2_Point_Cal.setText(_translate("MainWindow", "跳过2点校机"))
        self.actionAll_Seriap_output_ON.setText(_translate("MainWindow", "打开所有输出"))
        self.actionMulti_commands.setText(_translate("MainWindow", "多行命令"))
        self.actionSave_2.setText(_translate("MainWindow", "保存"))
        self.actionExit_2.setText(_translate("MainWindow", "退出"))
