# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseWindow(object):
    def setupUi(self, DatabaseWindow):
        DatabaseWindow.setObjectName("DatabaseWindow")
        DatabaseWindow.resize(1047, 609)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DatabaseWindow.sizePolicy().hasHeightForWidth())
        DatabaseWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(DatabaseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.database_table = QtWidgets.QTableWidget(self.tab)
        self.database_table.setMinimumSize(QtCore.QSize(748, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.database_table.setFont(font)
        self.database_table.setAutoFillBackground(True)
        self.database_table.setLineWidth(2)
        self.database_table.setMidLineWidth(1)
        self.database_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.database_table.setWordWrap(False)
        self.database_table.setRowCount(126)
        self.database_table.setObjectName("database_table")
        self.database_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.database_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.database_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.database_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.database_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_table.setItem(7, 2, item)
        self.database_table.horizontalHeader().setVisible(True)
        self.database_table.horizontalHeader().setCascadingSectionResizes(True)
        self.database_table.horizontalHeader().setDefaultSectionSize(200)
        self.database_table.horizontalHeader().setHighlightSections(True)
        self.database_table.horizontalHeader().setSortIndicatorShown(False)
        self.database_table.horizontalHeader().setStretchLastSection(True)
        self.database_table.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.database_table)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        DatabaseWindow.setCentralWidget(self.centralwidget)
        self.actionExport = QtWidgets.QAction(DatabaseWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExport.setFont(font)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(DatabaseWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionabout = QtWidgets.QAction(DatabaseWindow)
        self.actionabout.setObjectName("actionabout")

        self.retranslateUi(DatabaseWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DatabaseWindow)

    def retranslateUi(self, DatabaseWindow):
        _translate = QtCore.QCoreApplication.translate
        DatabaseWindow.setWindowTitle(_translate("DatabaseWindow", "Database Window"))
        self.database_table.setSortingEnabled(False)
        item = self.database_table.horizontalHeaderItem(0)
        item.setText(_translate("DatabaseWindow", "Index"))
        item = self.database_table.horizontalHeaderItem(1)
        item.setText(_translate("DatabaseWindow", "Location"))
        item = self.database_table.horizontalHeaderItem(2)
        item.setText(_translate("DatabaseWindow", "Description"))
        item = self.database_table.horizontalHeaderItem(3)
        item.setText(_translate("DatabaseWindow", "Value"))
        __sortingEnabled = self.database_table.isSortingEnabled()
        self.database_table.setSortingEnabled(False)
        self.database_table.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DatabaseWindow", "Database"))
        self.actionExport.setText(_translate("DatabaseWindow", "导出到Excel"))
        self.actionExit.setText(_translate("DatabaseWindow", "Exit"))
        self.actionabout.setText(_translate("DatabaseWindow", "About"))
